
package it.smartcommunitylab.mobilityservice.services.service.tobike.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Web Service per inserimento anagrafica utenti
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TOBikeUtente", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", wsdlLocation = "file:/C:/workspace-GIT/smartcampus.service.tobike/src/main/resources/tobike.wsdl")
public class TOBikeUtente
    extends Service
{

    private final static URL TOBIKEUTENTE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.smartcommunitylab.mobilityservice.services.service.tobike.ws.TOBikeUtente.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = it.smartcommunitylab.mobilityservice.services.service.tobike.ws.TOBikeUtente.class.getResource(".");
            url = new URL(baseUrl, "http://service.tobike.it/service.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/workspace-GIT/smartcampus.service.tobike/src/main/resources/tobike.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TOBIKEUTENTE_WSDL_LOCATION = url;
    }

    public TOBikeUtente(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TOBikeUtente() {
        super(TOBIKEUTENTE_WSDL_LOCATION, new QName("c://inetub/wwwroot/webservice/Service.asmx", "TOBikeUtente"));
    }

    /**
     * 
     * @return
     *     returns TOBikeUtenteSoap
     */
    @WebEndpoint(name = "TOBikeUtenteSoap")
    public TOBikeUtenteSoap getTOBikeUtenteSoap() {
        return super.getPort(new QName("c://inetub/wwwroot/webservice/Service.asmx", "TOBikeUtenteSoap"), TOBikeUtenteSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TOBikeUtenteSoap
     */
    @WebEndpoint(name = "TOBikeUtenteSoap")
    public TOBikeUtenteSoap getTOBikeUtenteSoap(WebServiceFeature... features) {
        return super.getPort(new QName("c://inetub/wwwroot/webservice/Service.asmx", "TOBikeUtenteSoap"), TOBikeUtenteSoap.class, features);
    }

}
