
package it.smartcommunitylab.mobilityservice.services.service.tobike.ws;

import java.math.BigDecimal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TOBikeUtenteSoap", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TOBikeUtenteSoap {


    /**
     * Tipologie di tessera disponibili
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ArrayOfTipoTessera
     */
    @WebMethod(operationName = "TipiTessera", action = "c://inetub/wwwroot/webservice/Service.asmx/TipiTessera")
    @WebResult(name = "TipiTesseraResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "TipiTessera", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TipiTessera")
    @ResponseWrapper(localName = "TipiTesseraResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TipiTesseraResponse")
    public ArrayOfTipoTessera tipiTessera(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore);

    /**
     * Tipologie di abbonamento disponibili
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ArrayOfTipoAbbonamento
     */
    @WebMethod(operationName = "TipiAbbonamento", action = "c://inetub/wwwroot/webservice/Service.asmx/TipiAbbonamento")
    @WebResult(name = "TipiAbbonamentoResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "TipiAbbonamento", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TipiAbbonamento")
    @ResponseWrapper(localName = "TipiAbbonamentoResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TipiAbbonamentoResponse")
    public ArrayOfTipoAbbonamento tipiAbbonamento(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore);

    /**
     * Ricerca utente
     * 
     * @param eMail
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ReturnMSG
     */
    @WebMethod(operationName = "RicercaUtente", action = "c://inetub/wwwroot/webservice/Service.asmx/RicercaUtente")
    @WebResult(name = "RicercaUtenteResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "RicercaUtente", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.RicercaUtente")
    @ResponseWrapper(localName = "RicercaUtenteResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.RicercaUtenteResponse")
    public ReturnMSG ricercaUtente(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "EMail", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String eMail);

    /**
     * Ricerca tessera utente
     * 
     * @param datiAnagrafici
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @param ricercaTesseraUtenteResult
     */
    @WebMethod(operationName = "RicercaTesseraUtente", action = "c://inetub/wwwroot/webservice/Service.asmx/RicercaTesseraUtente")
    @RequestWrapper(localName = "RicercaTesseraUtente", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.RicercaTesseraUtente")
    @ResponseWrapper(localName = "RicercaTesseraUtenteResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.RicercaTesseraUtenteResponse")
    public void ricercaTesseraUtente(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "DatiAnagrafici", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", mode = WebParam.Mode.INOUT)
        Holder<AnagraficaUtente> datiAnagrafici,
        @WebParam(name = "RicercaTesseraUtenteResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", mode = WebParam.Mode.OUT)
        Holder<ReturnMSG> ricercaTesseraUtenteResult);

    /**
     * Ricerca la prima tessera disponibile del rivenditore
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PrimaTesseraDisponibile", action = "c://inetub/wwwroot/webservice/Service.asmx/PrimaTesseraDisponibile")
    @WebResult(name = "PrimaTesseraDisponibileResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "PrimaTesseraDisponibile", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.PrimaTesseraDisponibile")
    @ResponseWrapper(localName = "PrimaTesseraDisponibileResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.PrimaTesseraDisponibileResponse")
    public String primaTesseraDisponibile(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore);

    /**
     * Ricerca tutte le tessere disponibili del rivenditore
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ArrayOfString
     */
    @WebMethod(operationName = "TessereDisponibili", action = "c://inetub/wwwroot/webservice/Service.asmx/TessereDisponibili")
    @WebResult(name = "TessereDisponibiliResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "TessereDisponibili", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TessereDisponibili")
    @ResponseWrapper(localName = "TessereDisponibiliResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TessereDisponibiliResponse")
    public ArrayOfString tessereDisponibili(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore);

    /**
     * Ricerca tutte le tessere utilizzate del rivenditore
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ArrayOfString
     */
    @WebMethod(operationName = "TessereNonDisponibili", action = "c://inetub/wwwroot/webservice/Service.asmx/TessereNonDisponibili")
    @WebResult(name = "TessereNonDisponibiliResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "TessereNonDisponibili", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TessereNonDisponibili")
    @ResponseWrapper(localName = "TessereNonDisponibiliResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TessereNonDisponibiliResponse")
    public ArrayOfString tessereNonDisponibili(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore);

    /**
     * Verifica se una tessera e' stata gia' assegnata ad un utente
     * 
     * @param numeroTessera
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "TesseraDisponibile", action = "c://inetub/wwwroot/webservice/Service.asmx/TesseraDisponibile")
    @WebResult(name = "TesseraDisponibileResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "TesseraDisponibile", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TesseraDisponibile")
    @ResponseWrapper(localName = "TesseraDisponibileResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TesseraDisponibileResponse")
    public boolean tesseraDisponibile(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "NumeroTessera", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String numeroTessera);

    /**
     * Inserisce un nuovo utente e associa la prima tessera disponibile
     * 
     * @param idModalitaPagamento
     * @param passwordRivenditore
     * @param inserisciResult
     * @param usernameRivenditore
     * @param ana
     */
    @WebMethod(operationName = "Inserisci", action = "c://inetub/wwwroot/webservice/Service.asmx/Inserisci")
    @RequestWrapper(localName = "Inserisci", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.Inserisci")
    @ResponseWrapper(localName = "InserisciResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.InserisciResponse")
    public void inserisci(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "ana", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", mode = WebParam.Mode.INOUT)
        Holder<AnagraficaUtente> ana,
        @WebParam(name = "IDModalitaPagamento", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", mode = WebParam.Mode.INOUT)
        Holder<Integer> idModalitaPagamento,
        @WebParam(name = "InserisciResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", mode = WebParam.Mode.OUT)
        Holder<ReturnMSG> inserisciResult);

    /**
     * Inserisce un nuovo utente e associa una tessera specifica
     * 
     * @param idModalitaPagamento
     * @param inserisciConNumeroTesseraResult
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @param ana
     * @param numeroTesseraSpecifico
     */
    @WebMethod(operationName = "InserisciConNumeroTessera", action = "c://inetub/wwwroot/webservice/Service.asmx/InserisciConNumeroTessera")
    @RequestWrapper(localName = "InserisciConNumeroTessera", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.InserisciConNumeroTessera")
    @ResponseWrapper(localName = "InserisciConNumeroTesseraResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.InserisciConNumeroTesseraResponse")
    public void inserisciConNumeroTessera(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "NumeroTesseraSpecifico", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String numeroTesseraSpecifico,
        @WebParam(name = "ana", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", mode = WebParam.Mode.INOUT)
        Holder<AnagraficaUtente> ana,
        @WebParam(name = "IDModalitaPagamento", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", mode = WebParam.Mode.INOUT)
        Holder<Integer> idModalitaPagamento,
        @WebParam(name = "InserisciConNumeroTesseraResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", mode = WebParam.Mode.OUT)
        Holder<ReturnMSG> inserisciConNumeroTesseraResult);

    /**
     * Inserisce un nuovo utente (solo dati anagrafici e di accesso)
     * 
     * @param inserisciSoloAnagraficaResult
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @param ana
     */
    @WebMethod(operationName = "InserisciSoloAnagrafica", action = "c://inetub/wwwroot/webservice/Service.asmx/InserisciSoloAnagrafica")
    @RequestWrapper(localName = "InserisciSoloAnagrafica", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.InserisciSoloAnagrafica")
    @ResponseWrapper(localName = "InserisciSoloAnagraficaResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.InserisciSoloAnagraficaResponse")
    public void inserisciSoloAnagrafica(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "ana", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", mode = WebParam.Mode.INOUT)
        Holder<AnagraficaUtente> ana,
        @WebParam(name = "InserisciSoloAnagraficaResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", mode = WebParam.Mode.OUT)
        Holder<ReturnMSG> inserisciSoloAnagraficaResult);

    /**
     * Elenca le stazioni ed il loro stato attuale
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ArrayOfString
     */
    @WebMethod(operationName = "ElencoStazioni", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoStazioni")
    @WebResult(name = "ElencoStazioniResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoStazioni", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioni")
    @ResponseWrapper(localName = "ElencoStazioniResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniResponse")
    public ArrayOfString elencoStazioni(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore);

    /**
     * Elenco semplificato delle stazioni e del loro stato attuale
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ArrayOfString
     */
    @WebMethod(operationName = "ElencoStazioniSemplice", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoStazioniSemplice")
    @WebResult(name = "ElencoStazioniSempliceResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoStazioniSemplice", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniSemplice")
    @ResponseWrapper(localName = "ElencoStazioniSempliceResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniSempliceResponse")
    public ArrayOfString elencoStazioniSemplice(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore);

    /**
     * Elenca le stazioni ed il loro stato attuale per specifico comune
     * 
     * @param codiceComune
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ArrayOfString
     */
    @WebMethod(operationName = "ElencoStazioniPerComune", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoStazioniPerComune")
    @WebResult(name = "ElencoStazioniPerComuneResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoStazioniPerComune", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniPerComune")
    @ResponseWrapper(localName = "ElencoStazioniPerComuneResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniPerComuneResponse")
    public ArrayOfString elencoStazioniPerComune(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "CodiceComune", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String codiceComune);

    /**
     * Elenco semplificato delle stazioni e del loro stato attuale per specifico comune
     * 
     * @param codiceComune
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ArrayOfString
     */
    @WebMethod(operationName = "ElencoStazioniSemplicePerComune", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoStazioniSemplicePerComune")
    @WebResult(name = "ElencoStazioniSemplicePerComuneResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoStazioniSemplicePerComune", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniSemplicePerComune")
    @ResponseWrapper(localName = "ElencoStazioniSemplicePerComuneResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniSemplicePerComuneResponse")
    public ArrayOfString elencoStazioniSemplicePerComune(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "CodiceComune", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String codiceComune);

    /**
     * Elenca le stazioni ed il loro stato attuale in JSON
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ElencoStazioniJSON", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoStazioniJSON")
    @WebResult(name = "ElencoStazioniJSONResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoStazioniJSON", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniJSON")
    @ResponseWrapper(localName = "ElencoStazioniJSONResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniJSONResponse")
    public String elencoStazioniJSON(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore);

    /**
     * Elenco semplificato delle stazioni e del loro stato attuale in JSON
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ElencoStazioniSempliceJSON", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoStazioniSempliceJSON")
    @WebResult(name = "ElencoStazioniSempliceJSONResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoStazioniSempliceJSON", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniSempliceJSON")
    @ResponseWrapper(localName = "ElencoStazioniSempliceJSONResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniSempliceJSONResponse")
    public String elencoStazioniSempliceJSON(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore);

    /**
     * Elenca le stazioni ed il loro stato attuale per specifico comune in JSON
     * 
     * @param codiceComune
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ElencoStazioniPerComuneJSON", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoStazioniPerComuneJSON")
    @WebResult(name = "ElencoStazioniPerComuneJSONResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoStazioniPerComuneJSON", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniPerComuneJSON")
    @ResponseWrapper(localName = "ElencoStazioniPerComuneJSONResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniPerComuneJSONResponse")
    public String elencoStazioniPerComuneJSON(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "CodiceComune", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String codiceComune);

    /**
     * Elenco semplificato delle stazioni e del loro stato attuale per specifico comune in JSON
     * 			
     * 
     * @param codiceComune
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ElencoStazioniSemplicePerComuneJSON", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoStazioniSemplicePerComuneJSON")
    @WebResult(name = "ElencoStazioniSemplicePerComuneJSONResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoStazioniSemplicePerComuneJSON", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniSemplicePerComuneJSON")
    @ResponseWrapper(localName = "ElencoStazioniSemplicePerComuneJSONResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoStazioniSemplicePerComuneJSONResponse")
    public String elencoStazioniSemplicePerComuneJSON(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "CodiceComune", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String codiceComune);

    /**
     * Crea tessera utente APP
     * 
     * @param s1
     * @param s
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreazioneTesseraAPP", action = "c://inetub/wwwroot/webservice/Service.asmx/CreazioneTesseraAPP")
    @WebResult(name = "CreazioneTesseraAPPResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "CreazioneTesseraAPP", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.CreazioneTesseraAPP")
    @ResponseWrapper(localName = "CreazioneTesseraAPPResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.CreazioneTesseraAPPResponse")
    public String creazioneTesseraAPP(
        @WebParam(name = "S", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String s,
        @WebParam(name = "S1", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String s1);

    /**
     * Transazione PayPal
     * 
     * @param p7
     * @param p6
     * @param p5
     * @param p4
     * @param p3
     * @param p2
     * @param p9
     * @param p8
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BTPay", action = "c://inetub/wwwroot/webservice/Service.asmx/BTPay")
    @WebResult(name = "BTPayResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "BTPay", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.BTPay")
    @ResponseWrapper(localName = "BTPayResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.BTPayResponse")
    public String btPay(
        @WebParam(name = "p2", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String p2,
        @WebParam(name = "p3", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String p3,
        @WebParam(name = "p4", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String p4,
        @WebParam(name = "p5", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        BigDecimal p5,
        @WebParam(name = "p6", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String p6,
        @WebParam(name = "p7", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String p7,
        @WebParam(name = "p8", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String p8,
        @WebParam(name = "p9", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String p9);

    /**
     * Dati abbonato in JSON
     * 
     * @param username
     * @param strCipherText
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DatiAbbonatoJSON", action = "c://inetub/wwwroot/webservice/Service.asmx/DatiAbbonatoJSON")
    @WebResult(name = "DatiAbbonatoJSONResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "DatiAbbonatoJSON", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.DatiAbbonatoJSON")
    @ResponseWrapper(localName = "DatiAbbonatoJSONResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.DatiAbbonatoJSONResponse")
    public String datiAbbonatoJSON(
        @WebParam(name = "username", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String username,
        @WebParam(name = "strCipherText", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String strCipherText);

    /**
     * Get chiave casuale
     * 
     * @param strUserName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRandomKey", action = "c://inetub/wwwroot/webservice/Service.asmx/GetRandomKey")
    @WebResult(name = "GetRandomKeyResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "GetRandomKey", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.GetRandomKey")
    @ResponseWrapper(localName = "GetRandomKeyResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.GetRandomKeyResponse")
    public String getRandomKey(
        @WebParam(name = "strUserName", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String strUserName);

    /**
     * Richiesta configurazione stazione
     * 
     * @param codiceComune
     * @param passwordRivenditore
     * @param codicePortale
     * @param usernameRivenditore
     * @param codiceStazione
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetStationConfiguration", action = "c://inetub/wwwroot/webservice/Service.asmx/GetStationConfiguration")
    @WebResult(name = "GetStationConfigurationResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "GetStationConfiguration", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.GetStationConfiguration")
    @ResponseWrapper(localName = "GetStationConfigurationResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.GetStationConfigurationResponse")
    public int getStationConfiguration(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "CodiceComune", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String codiceComune,
        @WebParam(name = "CodiceStazione", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String codiceStazione,
        @WebParam(name = "CodicePortale", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        int codicePortale);

    /**
     * Richiesta configurazione colonnina
     * 
     * @param codiceColonnina
     * @param codiceComune
     * @param passwordRivenditore
     * @param codicePortale
     * @param usernameRivenditore
     * @param codiceStazione
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetColumnConfiguration", action = "c://inetub/wwwroot/webservice/Service.asmx/GetColumnConfiguration")
    @WebResult(name = "GetColumnConfigurationResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "GetColumnConfiguration", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.GetColumnConfiguration")
    @ResponseWrapper(localName = "GetColumnConfigurationResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.GetColumnConfigurationResponse")
    public int getColumnConfiguration(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "CodiceComune", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String codiceComune,
        @WebParam(name = "CodiceStazione", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String codiceStazione,
        @WebParam(name = "CodiceColonnina", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String codiceColonnina,
        @WebParam(name = "CodicePortale", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        int codicePortale);

    /**
     * Ottiene la bici da Mobile
     * 
     * @param strIdstazione
     * @param strColonnina
     * @param strCipherText
     * @param strUserName
     * @return
     *     returns int
     */
    @WebMethod(operationName = "MobileGetBike", action = "c://inetub/wwwroot/webservice/Service.asmx/MobileGetBike")
    @WebResult(name = "MobileGetBikeResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "MobileGetBike", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.MobileGetBike")
    @ResponseWrapper(localName = "MobileGetBikeResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.MobileGetBikeResponse")
    public int mobileGetBike(
        @WebParam(name = "strCipherText", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String strCipherText,
        @WebParam(name = "strUserName", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String strUserName,
        @WebParam(name = "strIdstazione", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String strIdstazione,
        @WebParam(name = "strColonnina", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String strColonnina);

    /**
     * Ottiene lo username e la password di un utente di cui si conosce il tag badge e il comune
     * 			
     * 
     * @param idComune
     * @param tagBadge
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UsernamePasswordDaBadge", action = "c://inetub/wwwroot/webservice/Service.asmx/UsernamePasswordDaBadge")
    @WebResult(name = "UsernamePasswordDaBadgeResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "UsernamePasswordDaBadge", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.UsernamePasswordDaBadge")
    @ResponseWrapper(localName = "UsernamePasswordDaBadgeResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.UsernamePasswordDaBadgeResponse")
    public String usernamePasswordDaBadge(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "TagBadge", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String tagBadge,
        @WebParam(name = "IDComune", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        int idComune);

    /**
     * Ricava il codice del Comune per il calcolo del codice fiscale
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @param comune
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CodiceComuneCodice", action = "c://inetub/wwwroot/webservice/Service.asmx/CodiceComuneCodice")
    @WebResult(name = "CodiceComuneCodiceResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "CodiceComuneCodice", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.CodiceComuneCodice")
    @ResponseWrapper(localName = "CodiceComuneCodiceResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.CodiceComuneCodiceResponse")
    public String codiceComuneCodice(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "Comune", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String comune);

    /**
     * Calcola il codice fiscale
     * 
     * @param comuneNascita
     * @param dataNascita
     * @param passwordRivenditore
     * @param nome
     * @param usernameRivenditore
     * @param cognome
     * @param sesso
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CalcolaCodiceFiscale", action = "c://inetub/wwwroot/webservice/Service.asmx/CalcolaCodiceFiscale")
    @WebResult(name = "CalcolaCodiceFiscaleResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "CalcolaCodiceFiscale", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.CalcolaCodiceFiscale")
    @ResponseWrapper(localName = "CalcolaCodiceFiscaleResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.CalcolaCodiceFiscaleResponse")
    public String calcolaCodiceFiscale(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "Cognome", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String cognome,
        @WebParam(name = "Nome", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String nome,
        @WebParam(name = "DataNascita", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        XMLGregorianCalendar dataNascita,
        @WebParam(name = "ComuneNascita", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String comuneNascita,
        @WebParam(name = "Sesso", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String sesso);

    /**
     * Elenco Comuni abilitati per singolo Portale
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @param idPortale
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ElencoComuniPerPortale", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoComuniPerPortale")
    @WebResult(name = "ElencoComuniPerPortaleResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoComuniPerPortale", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoComuniPerPortale")
    @ResponseWrapper(localName = "ElencoComuniPerPortaleResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoComuniPerPortaleResponse")
    public String elencoComuniPerPortale(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "IDPortale", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        int idPortale);

    /**
     * Elenco Comuni abilitati per singolo Portale APP
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @param idPortale
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ElencoComuniPerPortaleAPP", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoComuniPerPortaleAPP")
    @WebResult(name = "ElencoComuniPerPortaleAPPResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoComuniPerPortaleAPP", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoComuniPerPortaleAPP")
    @ResponseWrapper(localName = "ElencoComuniPerPortaleAPPResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoComuniPerPortaleAPPResponse")
    public String elencoComuniPerPortaleAPP(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "IDPortale", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        int idPortale);

    /**
     * Elenco Comuni abilitati per singolo Portale in JSON
     * 
     * @param passwordRivenditore
     * @param usernameRivenditore
     * @param idPortale
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ElencoComuniPerPortaleJSON", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoComuniPerPortaleJSON")
    @WebResult(name = "ElencoComuniPerPortaleJSONResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoComuniPerPortaleJSON", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoComuniPerPortaleJSON")
    @ResponseWrapper(localName = "ElencoComuniPerPortaleJSONResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoComuniPerPortaleJSONResponse")
    public String elencoComuniPerPortaleJSON(
        @WebParam(name = "UsernameRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String usernameRivenditore,
        @WebParam(name = "PasswordRivenditore", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String passwordRivenditore,
        @WebParam(name = "IDPortale", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        int idPortale);

    /**
     * Crea anagrafica utente APP
     * 
     * @param s
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreazioneUtenteAPP", action = "c://inetub/wwwroot/webservice/Service.asmx/CreazioneUtenteAPP")
    @WebResult(name = "CreazioneUtenteAPPResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "CreazioneUtenteAPP", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.CreazioneUtenteAPP")
    @ResponseWrapper(localName = "CreazioneUtenteAPPResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.CreazioneUtenteAPPResponse")
    public String creazioneUtenteAPP(
        @WebParam(name = "S", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String s);

    /**
     * Lista viaggi utente APP
     * 
     * @param s
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ViaggiUtenteAPP", action = "c://inetub/wwwroot/webservice/Service.asmx/ViaggiUtenteAPP")
    @WebResult(name = "ViaggiUtenteAPPResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ViaggiUtenteAPP", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ViaggiUtenteAPP")
    @ResponseWrapper(localName = "ViaggiUtenteAPPResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ViaggiUtenteAPPResponse")
    public String viaggiUtenteAPP(
        @WebParam(name = "S", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String s);

    /**
     * Dati utente APP
     * 
     * @param username
     * @param strCipherText
     * @param lingua
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DatiUtenteAPP", action = "c://inetub/wwwroot/webservice/Service.asmx/DatiUtenteAPP")
    @WebResult(name = "DatiUtenteAPPResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "DatiUtenteAPP", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.DatiUtenteAPP")
    @ResponseWrapper(localName = "DatiUtenteAPPResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.DatiUtenteAPPResponse")
    public String datiUtenteAPP(
        @WebParam(name = "username", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String username,
        @WebParam(name = "lingua", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String lingua,
        @WebParam(name = "strCipherText", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String strCipherText);

    /**
     * Elenco Abbonamenti per Comune
     * 
     * @param s
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ElencoAbbonamentiPerComune", action = "c://inetub/wwwroot/webservice/Service.asmx/ElencoAbbonamentiPerComune")
    @WebResult(name = "ElencoAbbonamentiPerComuneResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "ElencoAbbonamentiPerComune", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoAbbonamentiPerComune")
    @ResponseWrapper(localName = "ElencoAbbonamentiPerComuneResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.ElencoAbbonamentiPerComuneResponse")
    public String elencoAbbonamentiPerComune(
        @WebParam(name = "S", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String s);

    /**
     * Totem richiede i tipi di abbonamento del Comune
     * 
     * @param x
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TotemTipiAbbonamenti", action = "c://inetub/wwwroot/webservice/Service.asmx/TotemTipiAbbonamenti")
    @WebResult(name = "TotemTipiAbbonamentiResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "TotemTipiAbbonamenti", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TotemTipiAbbonamenti")
    @ResponseWrapper(localName = "TotemTipiAbbonamentiResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TotemTipiAbbonamentiResponse")
    public String totemTipiAbbonamenti(
        @WebParam(name = "X", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String x);

    /**
     * Totem richiede invio SMS di verifica
     * 
     * @param x
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TotemInvioSMS", action = "c://inetub/wwwroot/webservice/Service.asmx/TotemInvioSMS")
    @WebResult(name = "TotemInvioSMSResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "TotemInvioSMS", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TotemInvioSMS")
    @ResponseWrapper(localName = "TotemInvioSMSResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TotemInvioSMSResponse")
    public String totemInvioSMS(
        @WebParam(name = "X", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String x);

    /**
     * Totem richiede controllo del codice di sicurezza inviato via SMS
     * 
     * @param x
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TotemControlloSMS", action = "c://inetub/wwwroot/webservice/Service.asmx/TotemControlloSMS")
    @WebResult(name = "TotemControlloSMSResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "TotemControlloSMS", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TotemControlloSMS")
    @ResponseWrapper(localName = "TotemControlloSMSResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TotemControlloSMSResponse")
    public String totemControlloSMS(
        @WebParam(name = "X", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String x);

    /**
     * Totem richiede i tipi di pagamento accettati dal comune
     * 
     * @param x
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TotemTipiPagamenti", action = "c://inetub/wwwroot/webservice/Service.asmx/TotemTipiPagamenti")
    @WebResult(name = "TotemTipiPagamentiResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "TotemTipiPagamenti", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TotemTipiPagamenti")
    @ResponseWrapper(localName = "TotemTipiPagamentiResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TotemTipiPagamentiResponse")
    public String totemTipiPagamenti(
        @WebParam(name = "X", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String x);

    /**
     * Totem conferma la transazione
     * 
     * @param x
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TotemSalvaTransazione", action = "c://inetub/wwwroot/webservice/Service.asmx/TotemSalvaTransazione")
    @WebResult(name = "TotemSalvaTransazioneResult", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
    @RequestWrapper(localName = "TotemSalvaTransazione", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TotemSalvaTransazione")
    @ResponseWrapper(localName = "TotemSalvaTransazioneResponse", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx", className = "it.smartcommunitylab.mobilityservice.services.test.service.tobike.ws.TotemSalvaTransazioneResponse")
    public String totemSalvaTransazione(
        @WebParam(name = "X", targetNamespace = "c://inetub/wwwroot/webservice/Service.asmx")
        String x);

}
